### PR TITLE
fix(plugin): install plugins with shellParas, plugin zip package must…

### LINKED ISSUE #1017: if user install plugins with shellParas,   plugin zip package must have install.sh file
**Environment**:

- eKuiper version (e.g. `1.3.0`):  1.3.1
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Others:

**What happened and what you expected to happen**:
found missing install.sh in plugin package,
while user install the plugins with shellParas, the plugin install successful

expect: should return error when missing install.sh and  shellParas not nil

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by SuperRxan**
Close #1017  
Signed-off-by: Jianxiang Ran <rxan_embedded@163.com>

### CODE REVIEW

File: internal/plugin/native/manager.go [hunk 1]
```diff
@@ -486,6 +490,11 @@ func (rr *Manager) install(t plugin2.PluginType, name, src string, shellParas []
 			conf.Log.Infof(`run install script:%s`, outb.String())
 			conf.Log.Infof("install %s plugin %s", plugin2.PluginTypes[t], name)
 		}
+	} else if haveInstallParas && !haveInstallFile {
```
Comment (ngjaying) [inline internal/plugin/native/manager.go:493]: Suggest to do this earlier to avoid copy then deleting files

Comment (SuperRxan) [reply internal/plugin/native/manager.go]: ack

File: internal/plugin/native/manager.go [hunk 2]
```diff
@@ -408,6 +408,17 @@ func (rr *Manager) install(t plugin2.PluginType, name, src string, shellParas []
...
+		fileName := file.Name
+		if fileName == "install.sh" {
+			haveInstallFile = true
+		}
+	}
+	if len(shellParas) != 0 && !haveInstallFile {
+		return filenames, "", fmt.Errorf("have shell parameters : %s but no install.sh file", shellParas)
+	}
+
 	defer r.Close()
```
Comment (ngjaying) [inline internal/plugin/native/manager.go:422]: must add this before line 411

**Review by ngjaying — CHANGES_REQUESTED** [review]

**Review by ngjaying — APPROVED** [review]
