### PR TITLE
feat(sink): fix kafka sink plugin write delay , refactor to IOErr ret…

### LINKED ISSUE #1778: kafka sink take more than one second to send out message
**Environment**:  debian

- eKuiper version (e.g. `1.3.0`):   lfedge/ekuiper:1.10.0-alpha.0   
- Hardware configuration (e.g. `lscpu`): 
- OS (e.g. `cat /etc/os-release`): linux
- Others:

**What happened and what you expected to happen**:

What happened:
kafka sink take more than one second to send out message
Another minor problem, when delivering message fails, if the error is recoverable, we should return error message starts with IOError, so that the sink cache can take effect. Check #1767 as an example.

What you expected to happen:
kafka sink should take less than 100 ms to send out message

**How to reproduce it (as minimally and precisely as possible)**:
use kafka sink to send data into kafka broker
check the metrics for rule

image

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by carlclone**
…ry mechanism

Closes #1778

### CODE REVIEW

File: extensions/sinks/kafka/kafka.go [hunk 1]
```diff
@@ -133,78 +133,31 @@ func (m *kafkaSink) Collect(ctx api.StreamContext, item interface{}) error {
...
-				case nil:
+	err := m.writer.WriteMessages(ctx, messages...)
+	switch err := err.(type) {
+	case kafkago.Error:
+		if err.Temporary() {
+			return fmt.Errorf(`%s: kafka sink fails to send out the data . %v`, errorx.IOErr, err)
+		}
+	case kafkago.WriteErrors:
+		count := 0
+		for i, _ := range messages {
```
Comment (ngjaying) [inline extensions/sinks/kafka/kafka.go:144]: Please fix the lint

File: extensions/sinks/kafka/kafka_test.go [hunk 2]
```diff
@@ -0,0 +1,73 @@
...
+
+package main
+
+import (
+	"testing"
+)
+
+func TestKafkaSink(t *testing.T) {
+
+	//sink := Kafka()
```
Comment (ngjaying) [inline extensions/sinks/kafka/kafka_test.go:23]: Still in draft?

**Review by superrxan — APPROVED** [review]
