### PR TITLE
fix (function): make aggregate functions return the same value as the SQL for empty Windows

### LINKED ISSUE #1682: Consistent aggregate function return value for empty window
Optimization Function Print Log （max、min）

### PR DESCRIPTION
**Pull request by Rui-Gan**
Closes #1682

### CODE REVIEW

**Review by superrxan — APPROVED** [review]

File: internal/binder/function/funcs_agg.go [hunk 1]
```diff
@@ -487,7 +509,7 @@ func dedup(r []interface{}, col []interface{}, all bool) (interface{}, error) {
 	}
 	if !all {
 		if len(result) == 0 {
-			return nil, nil
+			return []interface{}{}, nil
```
Comment (ngjaying) [inline internal/binder/function/funcs_agg.go:512]: The second argument 'all' means whether to reutrn the full array or just a single event. Here, we need to return a single event -> nil

**Review by ngjaying — CHANGES_REQUESTED** [review]

**Review by ngjaying — APPROVED** [review]
